dist: bionic
addons:
  apt:
    packages:
    - cmake
    - libgtest-dev
    - doxygen
    - graphviz
language: cpp
script:
- doxygen Doxyfile
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb -upaulokoelio:$BINTRAY_API_KEY "https://api.bintray.com/content/paulokoelio/otus10hw4/print_ip/1.0.$TRAVIS_BUILD_NUMBER/print_ip-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master
  local_dir: ./doc/html